name: Discord Release Notification
on:
  release:
    types: [published]
  workflow_dispatch:  
    inputs:
      test_version:
        description: 'Test version number'
        default: '1.0.0-test'


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          VERSION="${{ github.event.release.tag_name || github.event.inputs.test_version }}"
          REPO="${{ github.event.repository.name }}"
          URL="${{ github.event.release.html_url || github.server_url }}/${{ github.repository }}"
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"**v${VERSION} release of ${REPO} available now on GitHub**\n${URL}\"}" \
               $DISCORD_WEBHOOK